import sys
def welcome():
	sys.stdout.write("\n")
	sys.stdout.write("Welcome to...")
	sys.stdout.write("                             ,,                                  \n")
	sys.stdout.write("`7MM```Mq.                   db                    mm            \n")
	sys.stdout.write("  MM   `MM.                                        MM            \n")
	sys.stdout.write("  MM   ,M9 `7Mb,od8 ,pW`Wq.`7MM  .gP`Ya   ,p6`bo mmMMmm          \n")
	sys.stdout.write("  MMmmdM9    MM` ``6W`   `Wb MM ,M`   Yb 6M`  OO   MM            \n")
	sys.stdout.write("  MM         MM    8M     M8 MM 8M`````` 8M        MM            \n")
	sys.stdout.write("  MM         MM    YA.   ,A9 MM YM.    , YM.    ,  MM            \n")
	sys.stdout.write(".JMML.     .JMML.   `Ybmd9`  MM  `Mbmmd`  YMbmd`   `Mbmo         \n")
	sys.stdout.write("  .g8``bgd                QO MP                                  \n")
	sys.stdout.write(".dP`     `M               `bmP                                   \n")
	sys.stdout.write("dM`       ``7M`   `MF``7MMpdMAo.`7Mb,od8 .gP`Ya  ,pP`Ybd ,pP`Ybd \n")
	sys.stdout.write("MM           VA   ,V    MM   `Wb  MM` ``,M`   Yb 8I   `` 8I   `` \n")
	sys.stdout.write("MM.           VA ,V     MM    M8  MM    8M`````` `YMMMa. `YMMMa. \n")
	sys.stdout.write("`Mb.     ,`    VVV      MM   ,AP  MM    YM.    , L.   I8 L.   I8 \n")
	sys.stdout.write("  ``bmmmd`     ,V       MMbmmd` .JMML.   `Mbmmd` M9mmmP` M9mmmP` \n")
	sys.stdout.write("              ,V        MM                                       \n")
	sys.stdout.write("           OOb`       .JMML.                                     \n")
	sys.stdout.write("\n")
        sys.stdout.write("A project by some guys at Georgia Tech who love their \n")
        sys.stdout.write("neighborhood bar, Cypress Pint & Plate. Order the House.\n\n")
